version: '3'

# Each service runs in a separate container
services:

# the name of the service

  # the name of the service      
  postgres-db:
    container_name: music-db
    image: postgres:latest
    restart: always
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5000
      POSTGRES_DB: gitMusic
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5000:5000"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kevin.o.foreman2@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8001:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-db

volumes:
  pgdatasource:
  pgadmin-data: